services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  
  Libeo\LboLinks\EventListener\LinkModifier:
    tags:
      - name: event.listener
        identifier: LboLinkModifier
